### ISSUE TITLE
GPL 2.0 dependency: colorize gem

### ISSUE THREAD

**Issue by jordanbyron** [rubyatscale/packs#100]
Hi Team!

I noticed today that this gem has a dependency on the `colorize` gem which is released under the [GPL-2 license](https://github.com/fazibear/colorize/blob/master/LICENSE). Unfortunately, this license is incompatible with the project I'd like to use `packs` in. I have two questions (and if this would be better as a discussion I'm happy to close this issue and move it)

1. Would you be open to removing this dependency and replacing it with a gem with a more permissive license or even forgoing the coloring feature all together?
2. My understanding of the GPL-2 license is that any linked source needs to also be released under the same license. `packs` is MIT, not GPL-2. Is that not a problem for this project as well?

Thank you for your consideration.

**Comment by alexevanczuk** [comment]
@jordanbyron Thanks for catching this! 

I just merged https://github.com/rubyatscale/packs/pull/102 in order to resolve this. Let me know if you have any other concerns.

**Comment by jordanbyron** [comment]
No worries. Thanks for the quick turn around! 🚀
