### ISSUE TITLE
packs 0.0.24 (current latest release) is not compatible with visualize_packs 0.5.x

### ISSUE THREAD

**Issue by oboxodo** [rubyatscale/packs#101]
@shageman has released v0.5.x of visualize_packs with lots of changes but that version breaks compatibility with previous versions. In particular, I'm getting an error when using `bin/packs visualize` with packs 0.0.24 and visualize_packs 0.5.3 coming from [this line](https://github.com/rubyatscale/packs/blob/74ec6605483f5393f952e8f6acb79e57848a733c/lib/packs/private.rb#L592C29-L592C29).

```
/home/oboxodo/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/visualize_packs-0.5.3/lib/visualize_packs.rb:11:in `package_graph!': wrong number of arguments (given 1, expected 3) (ArgumentError)
	from /home/oboxodo/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/packs-0.0.24/lib/packs/private.rb:592:in `visualize'
```

Maybe `packs` should specify `< 0.5` for visualize_packs until assing support for the new version.

**Comment by shageman** [comment]
Sorry about that! I will get a fix out asap

**Comment by oboxodo** [comment]
Closing as this got solved in https://github.com/rubyatscale/packs/pull/103 and then further in https://github.com/rubyatscale/packs/pull/107.
