### ISSUE TITLE
Proposal: when moving a pack, rename all references

### ISSUE THREAD

**Issue by professor** [rubyatscale/packs#120]
When moving a pack to be inside another pack, the code currently searches and replaces for the pack name change inside files that this tooling controls (all the packs package.yml files).

However, when moving pack, we want all references to the old pack name updated including code references to files in the old pack.

I'm proposing we do something like:
```
`rg 'packs/#{pack}' -l --hidden | xargs sed -i '' 's,packs/#{old_pack_name},packs/#{new_pack_name},g'`
```

I realize that not all systems will have `ripgrep` installed.

**Comment by tstannard** [comment]
options: 

Add per_file_processors (similar to the codeowners one) that would run the find/replace on every file in the pack after move files [here](https://github.com/rubyatscale/packs/blob/cc48e856b0c36f96c540544399c4cc9b1dea4cd0/lib/packs/per_file_processor_interface.rb#L14C2-L14C2) 


Add line to readme

**Comment by professor** [comment]
Here's the time output for ripgrep vs grep


```
time rg 'packs/X' -l --hidden
0.91s user 8.30s system 218% cpu 4.207 total

time grep -r 'packs/X' .
93.78s user 33.24s system 14% cpu 14:25.44 total
```
