### ISSUE TITLE
Proposal: move pack to folder

### ISSUE THREAD

**Issue by professor** [rubyatscale/packs#135]
We’re currently moving many packs into folders. We were leveraging the `move_to_parent!` command in `bin/packs` and that helped us get going. However, `move_to_parent!` assumes you are moving a pack under a parent pack. This will then create a package.yml file if it doesn't exist. We don't want to do this.

I see two possible user experiences and three ways to implement this.

1) create a `move_to_folder` which does everything that `move_to_parent` does, but does not create a package.yml  

2) modify `move_to_parent` to take an argument about whether to create a package.yml

3) modify `move_to_parent` to never create a package.yml but modify it if it already exists.

## Existing User Experience

```
Existing options
‣ 1. Create a new pack
  2. Move files
  3. Add a dependency
  4. Get info on one or more packs
  5. Query violations about a pack
  6. Make files or directories public
  7. Move a child pack to be nested under a parent pack
  8. Rename a pack
  9. Run bin/packwerk check
  10. Run bin/packwerk update
  11. Run bin/packwerk validate (detects cycles)
  12. Lint packs/*/package.yml for one or more packs
```

## User Experience: Add a new option

Here's one possible user experience:

```
Existing options
‣ 1. Create a new pack
  2. Move files
  3. Move a pack <------------- new
  4. Add a dependency
  5. Get info on one or more packs
  6. Query violations about a pack
  7. Make files or directories public
  8. Move a child pack to be nested under a parent pack
  9. Rename a pack
  10. Run bin/packwerk check
  11. Run bin/packwerk update
  12. Run bin/packwerk validate (detects cycles)
  13. Lint packs/*/package.yml for one or more packs
```

```
Hello! What would you like to do? Move a pack
Please select a pack: packs/my_pack
Please input the destination directory: 
```

Pros
- I like how `move a pack` parallels with `move a file`

Cons
- I dislike that this will add another option to the bin/packs CLI command which already has 12 options.

## User Experience: repurpose an existing option

```
‣ 1. Create a new pack
  2. Move files
  3. Move a pack <------------- new
  4. Add a dependency
  5. Get info on one or more packs
  6. Query violations about a pack
  7. Make files or directories public
  8. Move a child pack to be nested under a parent pack <-------- deleted
  9. Rename a pack
  10. Run bin/packwerk check
  11. Run bin/packwerk update
  12. Run bin/packwerk validate (detects cycles)
  13. Lint packs/*/package.yml for one or more pack
```

```
Hello! What would you like to do? Move a pack to a folder or nested under a parent pack
Please select the pack to move: packs/my_pack
Would you like to 
‣ 1. Move to a folder
  2. Nest under a parent pack
 
# If picking 1
Please input the destination directory: 

# If picking 2
Please select the pack that will be the parent: 
```

I think *User Experience: repurpose an existing option*  is the winner.

Given this, we could rename `move_to_parent` to `move_pack` and have it never create a package.yml but modify it if it already exists.

**Comment by tstannard** [comment]
I'm mostly indifferent but I don't really mind adding a flag and being verbose a la option 2.

**Comment by perryqh** [comment]
Maybe we should consider deprecating `move to parent` and create `move to pack` that never creates a `package.yml`?

**Comment by schoblaska** [comment]
I like option 1 ("create a move_to_folder which does everything that move_to_parent does, but does not create a package.yml") and the UI option of having both be nested under the top-level "move a pack"

I think `move_to_parent` implies that the target is (or should be) a pack, so I don't think it makes sense to have a way of invoking that command that ignores the parent's package.yml.
