### ISSUE TITLE
Validation doesn't recognize "owner" in package.yml 

### ISSUE THREAD

**Issue by diogogallo** [rubyatscale/packs#142]
After creating a pack with the command `create` the file `package.yml` is created inside the new pack with the `owner` in the main level of the YML.

```
enforce_dependencies: true
enforce_privacy: true
owner: MyTeam
```

When running the `validate` command, it doesn't recognize the key `owner`:

> Validation failed ❗
> 
> ❓ Malformed syntax in the following manifests:
> 
> 	Unknown keys: ["owner"] in "/Users/diogogallo/workspace/x/domains/test/package.yml"

Looking at the `private.rb` the command below should not add `owner` as config but as `metadata`.
https://github.com/rubyatscale/packs/blob/6baf2e0ef0faeb64834c8405e1d99f41c2725214/lib/packs/private.rb#L486
```
if Pathname.new('config/code_ownership.yml').exist?
          config = {
            'owner' => team.nil? ? 'MyTeam' : team.name
          }
        else
          config = {}
        end
```

Adding the `metadata` before the `owner` it works:
```
enforce_dependencies: true
enforce_privacy: true
metadata:
  owner: MyTeam
```

**Comment by alexevanczuk** [comment]
You'll need to do a bit more setup in your `packwerk.yml` to support the top-level key. See [docs here](https://github.com/rubyatscale/code_ownership#package-based-ownership). 

Let me know if that works for ya!

**Comment by diogogallo** [comment]
Hey @alexevanczuk , thanks for answering. Still not working.  
We are using Glob-Based Ownership already, does both ownership declaration works together?

**Comment by alexevanczuk** [comment]
Yes, the use/non-use of glob-based ownership should not affect top-level `owner` keys in `package.yml` files.

Could you post your `packwerk.yml` file? That'd help debug if possible🙏🏼

**Comment by diogogallo** [comment]
This is what I have:
```
exclude:
  - "{bin,node_modules,script,tmp,vendor}/**/*"
  - engines/*/spec/dummy/**/*

package_paths:
  - "."
  - "engines/*/"
  - "domains/*/"
  - "domains/*/*"

parallel: true

require:
  - code_ownership
  - packwerk/privacy/checker
```

**Comment by alexevanczuk** [comment]
That's interesting, can you share how you're executing packwerk? Are you using bundle exec?

**Comment by alexevanczuk** [comment]
Nice! Glad it's working now.

No apologies needed. Thanks for sharing the issue you were having. We're here to help!

**Comment by diogogallo** [comment]
The problem was fixed recreating the `packwerk` stub
