### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by igorkasyanchuk** [rubyatscale/packs#144]
Hello, 

Experimenting with your gem and have a few questions. First of all I added gems:

```ruby
  gem "packwerk"
  gem "packs"
  gem "packs-rails"
```

1. packwerk init
2. packs create <pack-name>
3. trying to validate

Questions:

1. I see have this error:

<img width="1319" alt="image" src="https://github.com/rubyatscale/packs/assets/11101/ab1d29e6-42fa-4cc9-b3cd-85cf4fc0643f">

My structure:

<img width="697" alt="image" src="https://github.com/rubyatscale/packs/assets/11101/2ca38de7-4778-4502-b289-c175eaabbb97">

2.  Unknown keys: ["enforce_privacy"]

<img width="546" alt="image" src="https://github.com/rubyatscale/packs/assets/11101/8c17560c-b0f3-49f0-901f-b5fc0b6b2060">

<img width="1063" alt="image" src="https://github.com/rubyatscale/packs/assets/11101/25c6cfa4-d38f-40f5-9b0a-9943d9f3ee48">

3. Can I enforce privacy from my private code and not allow using my class (from packs/pack/services/service.rb) in regular folder app/models for example?

**Comment by shageman** [comment]
Hi Igor!

Been drafting this for too long, so will send a short version.

1.

I recommend not adding all the gems at the same time. Add `packs-rails` first and validate that you can move code into your packs folders. Then add `packwerk` and get dependency enforcement to work. At this stage you won't add `enforce_dependency`.

2. and 3.

Privacy is no longer in `packwerk`. You add `https://github.com/rubyatscale/packwerk-extensions` for that.


Do check out https://railsatscale.com/2024-01-26-a-packwerk-retrospective/ and read it with an eye towards privacy. Bottom line is: privacy (and the inverse: API design) takes a lot of work to get right. If you can't invest that work, you risk creating problems for yourself in the future.

**Comment by shageman** [comment]
This should probably be a discussion, not an issue...

**Comment by igorkasyanchuk** [comment]
thanks, will take a look
