### ISSUE TITLE
Gem name is not elegant

### ISSUE THREAD

**Issue by oleg-vinted** [rubyatscale/packs#18]
I realize this is VERY subjective, but I think it would make sense to rename the gem - or at least its CLI executable - to something more elegant. Having `_` in the name feels off, very rarely do CLI applications have underscores in their names.

Someone on the Modularity slack [mentioned `packwerker` as an option](https://rubymod.slack.com/archives/C0164JN9H5F/p1663112454946229?thread_ts=1663093617.026719&cid=C0164JN9H5F). This feels more elegant, but I'm afraid this can cause confusion about the relation between `packwerk` and `packwerker`.

I'm not proposing a specific name at this point though.

**Comment by edamamez** [comment]
Hi Oleg 👋 
Great point (and `packwerker` is too clever not to use somewhere 💡 ).
This may be something that you can do locally in the meantime by using a binstub to rename it.

**Comment by alexevanczuk** [comment]
Hey @oleg-vinted –

We were thinking of possibly renaming `use_packs` to just `packs` and renaming `packs` to `packs-specification`. What would you think of that?
