### ISSUE TITLE
Refactor CLI to better align non-interactive and interactive commands

### ISSUE THREAD

**Issue by alexevanczuk** [rubyatscale/packs#90]
`use_packs` has a CLI for interactive (via `bin/packs`) and non-interactive (via `bin/packs some_command`).

It's possible for these to drift, which I recently fixed so that every command is available in both interactive and non-interactive modes (except for `bin/packs list_top_dependency/privacy_violations`, which exists as `query` in the interactive commands).

There are some changes we could make to improve this.

Namely, if we redesign the commands so that a single file defines both the interactive and non interactive commands (e.g. through some interface), then by design we can ensure both are always populated.

Along with this we should probably add better tests for all commands CLI and non-CLI

**Comment by professor** [comment]
Closing as per Alex,
